// Copyright 2025 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';

import 'package:flutter/foundation.dart';

import '../model/catalog.dart';
import '../model/ui_models.dart';
import '../primitives/logging.dart';
import 'core_catalog.dart';

/// A sealed class representing an update to the UI managed by [SurfaceManager].
///
/// This class has three subclasses: [SurfaceAdded], [SurfaceUpdated], and
/// [SurfaceRemoved].
sealed class GenUiUpdate {
  /// Creates a [GenUiUpdate] for the given [surfaceId].
  const GenUiUpdate(this.surfaceId);

  /// The ID of the surface that was updated.
  final String surfaceId;
}

/// Fired when a new surface is created.
class SurfaceAdded extends GenUiUpdate {
  /// Creates a [SurfaceAdded] event for the given [surfaceId] and
  /// [definition].
  const SurfaceAdded(super.surfaceId, this.definition);

  /// The definition of the new surface.
  final UiDefinition definition;
}

/// Fired when an existing surface is modified.
class SurfaceUpdated extends GenUiUpdate {
  /// Creates a [SurfaceUpdated] event for the given [surfaceId] and
  /// [definition].
  const SurfaceUpdated(super.surfaceId, this.definition);

  /// The new definition of the surface.
  final UiDefinition definition;
}

/// Fired when a surface is deleted.
class SurfaceRemoved extends GenUiUpdate {
  /// Creates a [SurfaceRemoved] event for the given [surfaceId].
  const SurfaceRemoved(super.surfaceId);
}

/// A manager for the state of the generative UI.
///
/// This class is responsible for managing the state of all the UI "surfaces"
/// that are generated by the AI. It provides tools for the AI to manipulate
/// the UI, and it notifies listeners of changes to the UI.
class SurfaceManager {
  /// Creates a new [SurfaceManager].
  ///
  /// A [catalog] of UI components can be provided, otherwise the
  /// [coreCatalog] will be used.
  SurfaceManager({Catalog? catalog}) : catalog = catalog ?? coreCatalog;

  /// The catalog of UI components that can be used to build the UI.
  final Catalog catalog;

  final _surfaces = <String, ValueNotifier<UiDefinition?>>{};
  final _updates = StreamController<GenUiUpdate>.broadcast();

  /// A map of the current UI surfaces.
  Map<String, ValueNotifier<UiDefinition?>> get surfaces => _surfaces;

  /// A stream of updates to the UI.
  ///
  /// This stream emits a [GenUiUpdate] whenever a surface is added, updated,
  /// or removed.
  Stream<GenUiUpdate> get updates => _updates.stream;

  /// Returns a [ValueNotifier] for the given [surfaceId].
  ///
  /// This can be used to listen for changes to a specific surface.
  ValueNotifier<UiDefinition?> surface(String surfaceId) {
    return _surfaces.putIfAbsent(surfaceId, () => ValueNotifier(null));
  }

  /// Adds or updates a UI surface.
  ///
  /// This method is called to update the UI.
  void addOrUpdateSurface(String surfaceId, Map<String, Object?> definition) {
    final uiDefinition = UiDefinition.fromMap({
      'surfaceId': surfaceId,
      ...definition,
    });
    final notifier = surface(surfaceId); // Gets or creates the notifier.
    final isNew = notifier.value == null;
    notifier.value = uiDefinition;
    if (isNew) {
      genUiLogger.info('Adding surface $surfaceId');
      _updates.add(SurfaceAdded(surfaceId, uiDefinition));
    } else {
      genUiLogger.info('Updating surface $surfaceId');
      _updates.add(SurfaceUpdated(surfaceId, uiDefinition));
    }
  }

  /// Deletes a UI surface.
  ///
  /// This method is called to update the UI.
  void deleteSurface(String surfaceId) {
    if (_surfaces.containsKey(surfaceId)) {
      genUiLogger.info('Deleting surface $surfaceId');
      final notifier = _surfaces.remove(surfaceId);
      notifier?.dispose();
      _updates.add(SurfaceRemoved(surfaceId));
    }
  }

  /// Disposes of the resources used by the manager.
  void dispose() {
    _updates.close();
    for (final notifier in _surfaces.values) {
      notifier.dispose();
    }
  }
}
