// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux because '
          "Firebase AI Logic isn't supported on Linux",
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxByPgKNTJc4Gc5N0w2l-I5ffE-dWkVKg',
    appId: '1:975757934897:ios:540a1a4eeeb57afb0ff010',
    messagingSenderId: '975757934897',
    projectId: 'fluttergenui',
    storageBucket: 'fluttergenui.firebasestorage.app',
    iosBundleId: 'dev.flutter.genui.genuiClient',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAel-GAcyjdd83BickJkzf15mbZxyiOpfg',
    appId: '1:975757934897:android:1735467a70fdea1d0ff010',
    messagingSenderId: '975757934897',
    projectId: 'fluttergenui',
    storageBucket: 'fluttergenui.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwqYvj1Qe2odTlesCrD6tI7ZUzkax5BA',
    appId: '1:975757934897:web:818e744e0a7130da0ff010',
    messagingSenderId: '975757934897',
    projectId: 'fluttergenui',
    authDomain: 'fluttergenui.firebaseapp.com',
    storageBucket: 'fluttergenui.firebasestorage.app',
    measurementId: 'G-D2FN00RSD9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxByPgKNTJc4Gc5N0w2l-I5ffE-dWkVKg',
    appId: '1:975757934897:ios:540a1a4eeeb57afb0ff010',
    messagingSenderId: '975757934897',
    projectId: 'fluttergenui',
    storageBucket: 'fluttergenui.firebasestorage.app',
    iosBundleId: 'dev.flutter.genui.genuiClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZwqYvj1Qe2odTlesCrD6tI7ZUzkax5BA',
    appId: '1:975757934897:web:0152927eeb6b30320ff010',
    messagingSenderId: '975757934897',
    projectId: 'fluttergenui',
    authDomain: 'fluttergenui.firebaseapp.com',
    storageBucket: 'fluttergenui.firebasestorage.app',
    measurementId: 'G-Z3D9Q293KS',
  );
}
