// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfE4h245gUPNa3RhCYQ8e14RU2oBSYirY',
    appId: '1:686538628455:web:2c834d7c0edb094664a3c2',
    messagingSenderId: '686538628455',
    projectId: 'agent-demo-tj',
    authDomain: 'agent-demo-tj.firebaseapp.com',
    storageBucket: 'agent-demo-tj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmASpK1e_mOHGrNt6VU6RZEwZrNJ0cx_8',
    appId: '1:686538628455:android:6a3b1cf2fea3374864a3c2',
    messagingSenderId: '686538628455',
    projectId: 'agent-demo-tj',
    storageBucket: 'agent-demo-tj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpykF61GD5fHfdSRrcDk_xnf1JTekkPLw',
    appId: '1:686538628455:ios:4611001336b1aad664a3c2',
    messagingSenderId: '686538628455',
    projectId: 'agent-demo-tj',
    storageBucket: 'agent-demo-tj.firebasestorage.app',
    androidClientId: '686538628455-5fnq9mtf416g0jni848d1vsn0rti3iev.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.genuiClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpykF61GD5fHfdSRrcDk_xnf1JTekkPLw',
    appId: '1:686538628455:ios:4611001336b1aad664a3c2',
    messagingSenderId: '686538628455',
    projectId: 'agent-demo-tj',
    storageBucket: 'agent-demo-tj.firebasestorage.app',
    androidClientId: '686538628455-5fnq9mtf416g0jni848d1vsn0rti3iev.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.genuiClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfE4h245gUPNa3RhCYQ8e14RU2oBSYirY',
    appId: '1:686538628455:web:2c834d7c0edb094664a3c2',
    messagingSenderId: '686538628455',
    projectId: 'agent-demo-tj',
    authDomain: 'agent-demo-tj.firebaseapp.com',
    storageBucket: 'agent-demo-tj.firebasestorage.app',
  );

}